#!C:\Users\P0037503\source\repos\POC\image cleaner\Cropper\Cropper\env10\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
